### PR TITLE
fix: lex sort order of listobjects backend.Walk

### LINKED ISSUE #1283: [Bug] - ListObjects(V2) returns incorrect order with the same name directory and file objects
**Describe the bug**
`ListObjectsV2` retrun incorrectcly ordered objects list, if the bucket contains both directory and file objects with the same name.

**To Reproduce**
```bash
aws s3api create-bucket --bucket test

aws s3api put-object --bucket test --key obj+
aws s3api put-object --bucket test --key obj/
aws s3api put-object --bucket test --key obj1

aws s3api list-objects(-v2) --bucket test 
```

**Expected behavior**
The objects order in result should be: `obj+`, `obj/`, `obj1`, instead getting `obj/`, `obj+`, `obj1`

### PR DESCRIPTION
**Pull request by benmcclelland**
The original Walk function used the native WalkDir and ReadDir which did not
guarantee lexicographic ordering of results for cases where including directory
slash changes the sort order. This caused incorrect paginated responses because
S3 APIs require strict lexicographic ordering where directories with trailing
slashes sort correctly relative to files. For example, dir1/a.b/ must come
before dir1/a/ in the results, but fs.WalkDir was returning them in filesystem
sort order which reversed the order due to not taking in account the trailing
"/".

This also lead to cases of continuous looping of paginated listobjects results
when the marker was set out of order from the expected results.

To address this fundamental ordering issue, the entire directory traversal
mechanism was replaced with a custom lexicographic sorting approach. The new
implementation reads each directory's contents using ReadDir, then sorts the
entries using custom sort keys that append trailing slashes to directory paths.
This ensures that dir1/a.b/ correctly sorts before dir1/a/, as well as other
similar failing cases,  according to ASCII character ordering rules.

Fixes #1283

### CODE REVIEW

**Comment by benmcclelland** [comment]
verified the fixed ListObjectsV2_truncated_common_prefixes does not return truncated prefixes on aws:
```
% aws s3api list-objects-v2 --bucket $bucket | grep Key   
            "Key": "d1/f1",
            "Key": "d2/f2",
            "Key": "d3/f3",
            "Key": "d4/f4",
% aws s3api list-objects-v2 --bucket $bucket --delimiter "/" --max-items 3
{
    "CommonPrefixes": [
        {
            "Prefix": "d1/"
        },
        {
            "Prefix": "d2/"
        },
        {
            "Prefix": "d3/"
        },
        {
            "Prefix": "d4/"
        }
    ],
    "RequestCharged": null,
    "Prefix": ""
}
```

But at least on azurite, azure is returning truncated prefixes from `client.NewListBlobsHierarchyPager` with `MaxResults` set, I wonder if they know about this discrepancy.

File: tests/integration/tests.go [hunk 1]
```diff
@@ -6369,8 +6369,11 @@ func ListObjectsV2_truncated_common_prefixes(s *S3Conf) error {
 			return err
 		}
 
-		if !comparePrefixes([]string{"d1/", "d2/", "d3/"}, out.CommonPrefixes) {
-			return fmt.Errorf("expected the common prefixes to be %v, instead got %v", []string{"d1/", "d2/", "d3/"}, out.CommonPrefixes)
+		expected := []string{"d1/", "d2/", "d3/", "d4/"}
+
+		if !comparePrefixes(expected, out.CommonPrefixes) {
+			return fmt.Errorf("expected the common prefixes to be %v, instead got %v",
+				expected, sprintPrefixes(out.CommonPrefixes))
```
Comment (niksis02) [inline tests/integration/tests.go]: The test was correct originally: this shouldn't be the case.
The result is limited to be 3 by `maxKeys`(3) and it should return a truncated result with `d3/` as `NextMarker`

File: backend/walk.go
Comment (niksis02) [inline backend/walk.go:1]: We should most probably have the same issue with `ListObjectVersions`: the `Walk` method responsible for parsing filesystem to object versions.

Maybe we would rather do this with another PR ?

Comment (benmcclelland) [reply backend/walk.go:1]: yeah, lets check if its needed, and do that in a different pr. i dont currently have a failing test for that to verify a fix

Comment (niksis02) [reply backend/walk.go:1]: Technically `ListObjectVersions` is the same as `ListObjects(V2)` by appending the object versions in the result. So if we don't create any object versions, it should return the exact same entries with some additional metadata(versionId ...). So it should be reproducable for `ListObjectVersions` as well.

**Comment by benmcclelland** [comment]
> verified the fixed ListObjectsV2_truncated_common_prefixes does not return truncated prefixes on aws:
> 
> ```
> % aws s3api list-objects-v2 --bucket $bucket | grep Key   
>             "Key": "d1/f1",
>             "Key": "d2/f2",
>             "Key": "d3/f3",
>             "Key": "d4/f4",
> % aws s3api list-objects-v2 --bucket $bucket --delimiter "/" --max-items 3
> {
>     "CommonPrefixes": [
>         {
>             "Prefix": "d1/"
>         },
>         {
>             "Prefix": "d2/"
>         },
>         {
>             "Prefix": "d3/"
>         },
>         {
>             "Prefix": "d4/"
>         }
>     ],
>     "RequestCharged": null,
>     "Prefix": ""
> }
> ```
> 
> But at least on azurite, azure is returning truncated prefixes from `client.NewListBlobsHierarchyPager` with `MaxResults` set, I wonder if they know about this discrepancy.

aws command bug, they document the option as `--max-items`, but the real option (not documented correctly) is `--max-keys`. So the original test was correct.
