### PR TITLE
fix: update marker/continuation token to be the azure next marker

### LINKED ISSUE #1457: [Bug] VersityGW uses last key as continuation token which breaks Azure Go SDK pagination
**Description**

When using VersityGW with Azure Blob Storage as the backend and setting MaxKeys (e.g., to 2) while having more objects (e.g., 4), the first ListObjectsV2 call succeeds. However, the gateway returns the last key as the continuation token, and passing this token to the next call causes the Azure API to throw 400 Bad Request with InvalidQueryParameterValue.

**Steps to Reproduce**

1. Deploy VersityGW configured to use Azure Blob Storage as the backend.
2. Upload 4 objects to the bucket.
3. Call ListObjectsV2 with MaxKeys = 2.
4. Observe that the response returns the last object's key as ContinuationToken.
5. Use that token in the next ListObjectsV2 call — the response results in an error.

**Expected Behavior**

Azure’s pagination requires using the provided NextMarker from Azure responses, not simply the last retrieved key. If Azure returns a NextMarker, it should be used as the continuation token going forward.

**Actual Behavior**

VersityGW incorrectly uses the last key (from listing results) as the continuation token, rather than the Azure-provided NextMarker, causing invalid queries when passed to Azure.

Refer https://github.com/versity/versitygw/discussions/1410

### PR DESCRIPTION
**Pull request by benmcclelland**
This changes the marker/continuation token from the object name to the marker from the azure list objects pager. This is needed because passing the object name as the token to the azure next call causes the Azure API to throw 400 Bad Request with InvalidQueryParameterValue. So we have to use the azure marker for compatibility with the azure API pager.

Fixes #1457

### CODE REVIEW

**Comment by nitinosiris** [comment]
HI @benmcclelland, just pull these changes and tested it, getting the below error 
```
-----------------------------------------------------
┌─────────────────────────────────────────────────[ RESPONSE HEADERS ]─────────────────────────────────────────────────┐
│ Content-Type  : text/plain; charset=utf-8                                                                            │
│ Server        : VERSITYGW                                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
───────────────────────────────────────────────────[ RESPONSE BODY ]────────────────────────────────────────────────────
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidQueryParameterValue</Code><Message>400 Value for one of the query parameters specified in the request URI is invalid.</Message><Resource></Resource><RequestId></RequestId><HostId></HostId></Error>
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
03:46:29 | 400 |    7.856919ms | 127.0.0.1 | GET | /demo/ | - | continuation-token=edgev2.ps1&list-type=2&max-keys=2
```

continuation token should not be last object name!

**Comment by nitinosiris** [comment]
I used below code snippet for testing this 
```
 var request = new ListObjectsV2Request
 {
     BucketName = containerName,
     Prefix = subDirectoryPath,
     MaxKeys = 2
 };

 ListObjectsV2Response response;

 do
 {
     response = amazonS3Client.ListObjectsV2Async(request).GetAwaiter().GetResult();

     foreach (var blob in response.S3Objects)
     {
         var originalLength = blob.Size.ToString();

         var blobInfo = string.Format(CultureInfo.InvariantCulture, "{0},{1},{2},{3},{4},{5},{6},{7}", containerName, blob.Key,
             "BlockBlob",
             "application/octet-stream", blob.ETag, blob.LastModified,
             originalLength,
             originalLength);

         yield return blobInfo;
     }
     request.ContinuationToken = response.NextContinuationToken;
 }
 while (response.IsTruncated.GetValueOrDefault());
```

**Comment by nitinosiris** [comment]
This is how it should look like 
```
-----------------------------------------------------
┌─────────────────────────────────────────────────[ RESPONSE HEADERS ]─────────────────────────────────────────────────┐
│ Content-Length : 773                                                                                                 │
│ Content-Type  : application/xml                                                                                      │
│ Server        : VERSITYGW                                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
───────────────────────────────────────────────────[ RESPONSE BODY ]────────────────────────────────────────────────────
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>demo</Name><ContinuationToken>2!72!MDAwMDA5IW5pdGluLnR4dCEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-</ContinuationToken><MaxKeys>2</MaxKeys><IsTruncated>false</IsTruncated><Contents><LastModified>2025-08-20T03:45:07Z</LastModified><ChecksumType></ChecksumType><ETag>0x8DDDF9BF48CBA83-1</ETag><Key>nitin.txt</Key><Size>600</Size><StorageClass>STANDARD</StorageClass></Contents><Contents><LastModified>2025-08-12T05:58:15Z</LastModified><ChecksumType></ChecksumType><ETag>0x8DDD9653AACA5B5-1</ETag><Key>s3proxy-service-deployment.yaml.txt</Key><Size>1939</Size><StorageClass>STANDARD</StorageClass></Contents><EncodingType></EncodingType></ListBucketResult>
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
03:56:34 | 200 |    8.433893ms | 127.0.0.1 | GET | /demo/ | - | continuation-token=2%2172%21MDAwMDA5IW5pdGluLnR4dCEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-&list-type=2&max-keys=2
```

**Review by niksis02 — DISMISSED** [review]

**Comment by benmcclelland** [comment]
@nitinosiris I see what the issue was before, we can't mix the object name and azure markers for partial page results. So I think the tests have some bad assumptions for this case. I need to fix the tests or skip these with the azure backend, but I think this version of the code should pass your tests now. This is now just aligning the S3 ListObjects with the Azure ListBlobsHierarchyPager for a one to one in the paginated results. This should now always keep the marker as the Azure compatible marker. The tricky part was the StartAfter in the ListObjectV2 where you can specify the object to start listing from. For this case, its keep running through the Azure paginated results until it finds the start position. But this can be a partial page blob listing, so can return fewer results in the first call to list objects than the tests assume.

**Comment by nitinosiris** [comment]
HI @benmcclelland , yes the code snippet is working as expected now!

File: backend/azure/azure.go [hunk 1]
```diff
@@ -578,191 +578,133 @@ func (az *Azure) GetObjectAttributes(ctx context.Context, input *s3.GetObjectAtt
...
-	})
-
-	var objects []s3response.Object
-	var cPrefixes []types.CommonPrefix
-	var nextMarker *string
-	var isTruncated bool
-	var maxKeys int32 = math.MaxInt32
-	var fetchOwner bool
 
+	var maxKeys int32 = 10000
```
Comment (nitinosiris) [inline backend/azure/azure.go]: Just a suggestion though, aws sdk supports upto 1000 keys/per response and initializing it as 10000 could be misleading :)

Comment (benmcclelland) [reply backend/azure/azure.go]: oh! yes, that was a typo, thanks for catching that

**Comment by benmcclelland** [comment]
this still needs a little more work. turns out the list-objects marker is expected to be an object name, and when specified in the original request works like the start after in the v2 call. so while the list-objects-v2 can use the native azure marker as the continuation token, looks like we need to do a bit less optimal listings for the list-objects.

**Review by niksis02 — APPROVED** [review]
