### PR TITLE
fix: Adds validation for Content-Length in upload operations.

### LINKED ISSUE #961: [Bug] - UploadPart max size limit
**Describe the bug**
If uploading a part with a size greater than `5 GiB`, the `UploadPart` operation should fail.

**To Reproduce**
```bash
aws s3api create-bucket --bucket test

aws s3api create-multipart-upload --bucket test --key obj

// file_1 should be greater than 5Gib
aws s3api upload-part --bucket test --key obj --upload-id <mp_upload_id> --part-number 1 --body file_1
```

**Expected behavior**
`UploadPart` should return the following error:
```
An error occurred (EntityTooLarge) when calling the UploadPart operation: Your proposed upload exceeds the maximum allowed size
```

### LINKED ISSUE #1248: [Bug] - PutObject/UploadPart should fail, if content-length is missing
**Describe the bug**
`UploadPart` and `PutObject` should fail if `Content-Length` http header is missing.

**To Reproduce**
```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider("aws_access_key_id", "aws_secret_access_key", "")), config.WithRegion("us-east-1"))
	if err != nil {
		log.Fatal(err)
	}
	client := s3.NewFromConfig(cfg)
	pClient := s3.NewPresignClient(client)

	signed, err := pClient.PresignPutObject(context.Background(), &s3.PutObjectInput{
		Bucket: getString("bucket_name"),
		Key:    getString("object_key"),
	})
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Println(signed)
}

func getString(str string) *string {
	return &str
}

```

This script will print out the signed headers, presigned request URL and method(PUT).
Take the values and make an http request with `curl`:

```bash
curl -X PUT -H "Host: niksis02-bucket-1.s3.us-east-1.amazonaws.com" "the_provided_url"
```

**Expected behavior**
The curl command should fail with the following error:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MissingContentLength</Code><Message>You must provide the Content-Length HTTP header.</Message><RequestId>JVMCE4H0A5ZV3YPZ</RequestId><HostId>kMgzP94HZZMsqkU+++qarHGfNsTvr7S+O0xzGsZ9bCqt3N/ATmgupKKZk0rupphTKoqi9ilA6mg=</HostId></Error>
```

### PR DESCRIPTION
**Pull request by niksis02**
Fixes #961
Fixes #1248

The gateway should return a `MissingContentLength` error if the `Content-Length` HTTP header is missing for upload operations (`PutObject`, `UploadPart`).

The second fix involves enforcing a maximum object size limit of `5 * 1024 * 1024 * 1024` bytes (5 GB) by validating the value of the `Content-Length` header. If the value exceeds this limit, the gateway should return an `EntityTooLarge` error.

`Note`: Integration tests are skipped, as they get stuck in github pipelines.

### CODE REVIEW

File: s3api/utils/chunk-reader.go [hunk 1]
```diff
@@ -96,10 +101,20 @@ func IsStreamingPayload(str string) bool {
...
-	if decContLength == "" {
-		return nil, s3err.GetAPIError(s3err.ErrMissingDecodedContentLength)
+	decContLengthStr := ctx.Get("X-Amz-Decoded-Content-Length")
+	if decContLengthStr == "" {
+		return nil, s3err.GetAPIError(s3err.ErrMissingContentLength)
+	}
+	decContLength, err := strconv.ParseInt(decContLengthStr, 10, 64)
+	//TODO: not sure if InvalidRequest should be returned in this case
+	if err != nil {
+		return nil, s3err.GetAPIError(s3err.ErrInvalidRequest)
```
Comment (benmcclelland) [inline s3api/utils/chunk-reader.go:111]: can we get a debug log in here to print the actual error since we are dropping it

Comment (niksis02) [reply s3api/utils/chunk-reader.go:111]: Let me do this in the context of this ticket https://github.com/versity/versitygw/issues/1221

Comment (niksis02) [reply s3api/utils/chunk-reader.go:111]: We are missing debug logging in many places in chunk readers
