### PR TITLE
fix: enforce 5gb copy source object size threshold.

### LINKED ISSUE #1896: [Bug] - `CopyObject` 5GB+ object copy
**Describe the bug**
When attempting to `CopyObject` a `5GB+` object, S3 returns an error, while versitygw successfully copies the object. Note that a 5GB+ object can be uploaded only with multipart uploads.

**To Reproduce**
```bash
aws s3api create-bucket --bucket test

// create a 5GB+ object with multipart uplod
aws s3 cp large-file.bin s3://test/obj // large-file.bin is 5GB+

aws s3api copy-object --bucket test --key dst-obj --copy-source test/obj
```

**Expected behavior**
The following error has to be returned:
```
An error occurred (InvalidRequest) when calling the CopyObject operation: The specified copy source is larger than the maximum allowable size for a copy source: 5368709120
```

### PR DESCRIPTION
**Pull request by niksis02**
Fixes #1896

Enforces the S3 `5 GiB` copy source size limit across the posix and azure backends for `CopyObject` and `UploadPartCopy`, returning `InvalidRequest` when the source object exceeds the threshold.

The limit is now configurable via `--copy-object-threshold` (`VGW_COPY_OBJECT_THRESHOLD`, default 5 GiB).
A new `--mp-max-parts flag` (`VGW_MP_MAX_PARTS`, default `10000`) has been added to make multipart upload parts number limit configurable.

No integration test has been added, as GitHub Actions cannot reliably handle large objects.

### CODE REVIEW

File: backend/azure/azure.go
Comment (benmcclelland) [inline backend/azure/azure.go]: missing copyObjectThreshold

Comment (benmcclelland) [inline backend/azure/azure.go]: missing copyObjectThreshold

File: backend/posix/posix.go [hunk 1]
```diff
@@ -3079,6 +3091,9 @@ func (p *Posix) UploadPartCopy(ctx context.Context, upi *s3.UploadPartCopyInput)
 	if err != nil {
 		return s3response.CopyPartResult{}, fmt.Errorf("stat object: %w", err)
 	}
+	if fi.Size() > p.copyObjectThreshold {
```
Comment (benmcclelland) [inline backend/posix/posix.go]: I think this should be using length from backend.ParseCopySourceRange() instead of fi.Size()?

File: backend/posix/posix.go [hunk 2]
```diff
@@ -235,6 +246,7 @@ func New(rootdir string, meta meta.MetadataStorer, opts PosixOpts) (*Posix, erro
 		forceNoCopyFileRange: opts.ForceNoCopyFileRange,
 		validateBucketName:   opts.ValidateBucketNames,
 		actionLimiter:        semaphore.NewWeighted(int64(concurrencyOrDefault(opts.Concurrency))),
+		copyObjectThreshold:  opts.CopyObjectThreshold,
```
Comment (benmcclelland) [inline backend/posix/posix.go:249]: I think we need to wire this through for scoutfs as well in scoutfs_compat.go otherwise it will be setting this to 0.
