### PR TITLE
fix: adds bucket region in ListBuckets result

### LINKED ISSUE #1374: [Bug] - REST - ListBuckets response data is missing bucket regions
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Server Version**

**Additional context**
<!-- Describe s3 client and version if applicable.

### PR DESCRIPTION
**Pull request by niksis02**
Fixes #1374

Hardcodes the gateway region for each bucket entry in `ListBuckets` result as bucket region.

### CODE REVIEW

File: s3api/controllers/bucket-list.go [hunk 1]
```diff
@@ -51,8 +51,15 @@ func (c S3ApiController) ListBuckets(ctx *fiber.Ctx) (*Response, error) {
 			ContinuationToken: cToken,
 			Prefix:            prefix,
 		})
+	if err != nil {
+		return &Response{}, err
+	}
+
+	for i := range res.Buckets.Bucket {
+		res.Buckets.Bucket[i].BucketRegion = defaultRegion
```
Comment (benmcclelland) [inline s3api/controllers/bucket-list.go]: this needs to be the configured region, not always "us-east-1"

Comment (niksis02) [reply s3api/controllers/bucket-list.go]: Ahh, thanks. Well noticed !

**Review by benmcclelland — APPROVED** [review]
