### PR TITLE
fix: fixes list-limiters parsing and validation

### LINKED ISSUE #1794: [Bug] - `ListMultipartUploads` - invalid max-uplodas error message
**Describe the bug**
When `ListMultipartUploads` is called with an invalid `max-uploads` value, S3 returns a different error message than VersityGW:

* **S3:** `Provided max-uploads not an integer or within integer range`
* **versitygw:** `Argument max-uploads must be an integer between 0 and 2147483647.`

**To Reproduce**
```bash
aws s3api create-bucket --bucket test

aws s3api list-multipart-uploads --bucket test --max-uploads 2157483647
```

**Expected behavior**
The `ListMultipartUploads` call should return the following error:
```
An error occurred (InvalidArgument) when calling the ListMultipartUploads operation: Provided max-uploads not an integer or within integer range
```

### LINKED ISSUE #1804: [Bug] - List actions should return a different error for invalid max limiter
**Describe the bug**
There are two categories of errors related to max limiters in paginated listing actions (such as ListBucket, ListObjects, etc.):

1. **Completely invalid limiter values**
   These include non-numeric inputs or values outside the integer range.
   **S3 error message:**
   `Provided <arg_name> not an integer or within integer range.`

2. **Negative limiter values**
   **S3 error message:**
   `Argument <arg_name> must be an integer between 0 and 2147483647.`

The `<arg_name>` varies depending on the action:

* ListObjects → **max-keys**
* ListMultipartUploads → **max-uploads**
* ListParts → **max-parts**
* ListParts (partNumberMarker) → **part-number-marker**
* ListBuckets → **max-buckets**

Currently, the gateway returns the second error form for all types of invalid limiters, including completely invalid values.

**To Reproduce**
example for `ListObjects`:
```bash
aws s3api create-bucket --bucket test

aws s3api list-objects --bucket test --max-keys 49832749832798423
aws s3api list-objects --bucket test --max-keys -12
```

**Expected behavior**
The first call should return the first error described above, the second - second

### LINKED ISSUE #1806: [Bug] - `GetObjectAttributes` should ignore invalid `x-amz-max-parts` values
**Describe the bug**
Currently the gateway parses and validates the `x-amz-max-parts` request header in `GetObjectAttributes` and returns an error for invalid values. S3, on the other hand, ignores the invalid values.

**To Reproduce**
```bash
aws s3api create-bucket --bucket test

aws s3api put-object --bucket test --key obj
aws s3api get-object-attributes --bucket test --key obj --object-attributes "StorageClass" "ETag" "ObjectSize" "ObjectParts"
```

**Expected behavior**
The last call has to return a sucessful response.

### LINKED ISSUE #1809: [Bug] - `ListObjectVersions` - negative `max-keys`
**Describe the bug**
When calling `ListObjectVersions` with negative `max-keys`, the error message returned by S3 and versitygw differs, though they are the same `InvalidArgument` errors.
versitygw:
```
Argument maxKeys must be an integer between 0 and 2147483647.
```
s3:
```
max-keys cannot be negative
```

**To Reproduce**
```bash
aws s3api create-bucket --bucket test

aws s3api list-object-versions --bucket test --max-keys -1
```

**Expected behavior**
The `list-object-versions` call has to return the following error:
```
An error occurred (InvalidArgument) when calling the ListObjectVersions operation: max-keys cannot be negative
```

### PR DESCRIPTION
**Pull request by niksis02**
Fixes #1809
Fixes #1806
Fixes #1804
Fixes #1794

This PR focuses on correcting so-called "list-limiter" parsing and validation. The affected limiters include: `max-keys`, `max-uploads`, `max-parts`, `max-buckets`, `max-uploads` and `part-number-marker`. When a limiter value is outside the integer range, a specific `InvalidArgument` error is now returned. If the value is a valid integer but negative, a different `InvalidArgument` error is produced.

`max-buckets` has its own validation rules: completely invalid values and values outside the allowed range (`1 <= input <= 10000`) return distinct errors. For `ListObjectVersions`, negative `max-keys` values follow S3’s special-case behavior and return a different `InvalidArgument` error message.

Additionally, `GetObjectAttributes` now follows S3 semantics for `x-amz-max-parts`: S3 ignores invalid values, so the gateway now matches that behavior.

### CODE REVIEW

File: s3api/controllers/object-get.go [hunk 1]
```diff
@@ -362,16 +354,11 @@ func (c S3ApiController) GetObjectAttributes(ctx *fiber.Ctx) (*Response, error)
...
-	maxParts, err := utils.ParseUint(maxPartsStr)
-	if err != nil {
-		debuglogger.Logf("error parsing max parts %q: %v",
-			maxPartsStr, err)
-		return &Response{
-			MetaOpts: &MetaOptions{
-				BucketOwner: parsedAcl.Owner,
-			},
-		}, s3err.GetAPIError(s3err.ErrInvalidMaxParts)
+	parsed, err := utils.ParseMaxLimiter(maxPartsStr, utils.LimiterTypeMaxKeys)
```
Comment (benmcclelland) [inline s3api/controllers/object-get.go]: utils.LimiterTypeMaxParts instead of utils.LimiterTypeMaxKeys?
