### PR TITLE
fix: list objects trim common prefixes that match marker prefix

### LINKED ISSUE #778: s3 ls --page-size can return duplicate output
**Describe the bug**
See repro below - adding a combination of directory and file and then listing with a small page size results in duplicate lines in the output

**To Reproduce**
printf "File 100.\n" >file100.txt
d1aws s3api put-object --bucket ngenea-test --key dir14/subdir/file.txt --body file100.txt
d1aws s3api put-object --bucket ngenea-test --key dir14/subdir.ext --body file100.txt
d1aws s3 ls  --page-size=2 s3://ngenea-test/dir14/

OUTPUT:
{
    "ETag": "86c27a184101d828becca6ec4b65f3b8"
}
{
    "ETag": "86c27a184101d828becca6ec4b65f3b8"
}
                           PRE subdir/
2024-08-30 17:30:31         10 subdir.ext
                           PRE subdir/                       #      <<<<<<<<<<<<<<<<< ???

**Expected behavior**
No duplicate output

**Server Version**
built from clone on 30 aug 2024

**Additional context**

### PR DESCRIPTION
**Pull request by benmcclelland**
This checks to see if the common prefix is before the marker and thus would have been returned in earlier list objects request.

The error case was aws cli listing multiple entries for the same common prefix when the listing required multiple pagination requests.

Fixes #778

### CODE REVIEW

**Review by jonaustin09 — COMMENTED** [review]
Could you add an integration test case for paginated common prefixes ?

Could you make sure azure also handles this case correctly and passes the tests?

File: tests/integration/tests.go [hunk 1]
```diff
@@ -3601,6 +3601,49 @@ func ListObjects_with_prefix(s *S3Conf) error {
...
+}
+
+func pfxStrings(pfxs []types.CommonPrefix) []string {
+	pfxStrs := make([]string, len(pfxs))
+	for i, pfx := range pfxs {
+		pfxStrs[i] = *pfx.Prefix
+	}
+	return pfxStrs
+}
+
```
Comment (mlt180) [inline tests/integration/tests.go]: Maybe we should move this to utils.go?

**Review by jonaustin09 — APPROVED** [review]
