### PR TITLE
fix: unexpected errors during upload races

### LINKED ISSUE #854: concurrent uploading the same object sometimes results in the exception ExistingObjectIsDirectory
**Describe the bug**
concurrent uploading the same object sometimes results in the exception ExistingObjectIsDirectory. See script below

**To Reproduce**
#!/bin/bash

printf "abc\n" >body.txt

for ((ii=1; ii<=10; ii++)); do
    aws s3api put-object --endpoint-url http://10.60.0.32:7070/ --region us-east-1 --bucket test --key=object1 --body body.txt &
done

wait

OUTPUT:
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}

An error occurred (ExistingObjectIsDirectory) when calling the PutObject operation: Existing Object is a directory.
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}

**Expected behavior**
object upload to complete without error

**Server Version**
git clone from 25 sep 

**Additional context**

### PR DESCRIPTION
**Pull request by benmcclelland**
This fixes the cases for racing uploads with the same object names. Before we were making some bad assumptions about what would cause an error when trying to link/rename the final object name into the namespace, but missed the case that another upload for the same name could be racing with this upload and causing an incorrect error.

This also changes the order of setting metadata to prevent accidental setting of metadata for the current upload to another racing upload.

Fixes #854

### CODE REVIEW

File: backend/posix/posix.go [hunk 1]
```diff
@@ -153,8 +153,6 @@ func New(rootdir string, meta meta.MetadataStorer, opts PosixOpts) (*Posix, erro
 		if !vDir.IsDir() {
 			return nil, fmt.Errorf("versioning path should be a directory")
 		}
-
-		fmt.Printf("Bucket versioning enabled with directory: %v\n", verioningdirAbs)
```
Comment (mlt180) [inline backend/posix/posix.go:157]: Do we really need to remove the versioning configuration log?

**Review by jonaustin09 — COMMENTED** [review]
Looks like the implementation resolves the race condition of object versions upload mentioned in #841 . If it actually does, we could add the following integration test as well.
```
func Concurrent_upload_object_versions(s *S3Conf) error {
	testName := "Concurrent_upload_object_versions"
	return actionHandler(s, testName, func(s3client *s3.Client, bucket string) error {
		obj := "my-obj"
		versionCount := 5
		// Channel to collect errors
		errCh := make(chan error, versionCount)

		uploadVersion := func(wg *sync.WaitGroup) {
			defer wg.Done()

			ctx, cancel := context.WithTimeout(context.Background(), shortTimeout)
			res, err := s3client.PutObject(ctx, &s3.PutObjectInput{
				Bucket: &bucket,
				Key:    &obj,
			})
			cancel()
			if err != nil {
				// Send error to the channel
				errCh <- err
				return
			}

			fmt.Printf("uploaded object successfully: versionId: %v\n", *res.VersionId)
		}

		wg := &sync.WaitGroup{}
		wg.Add(versionCount)

		for i := 0; i < versionCount; i++ {
			go uploadVersion(wg)
		}

		wg.Wait()
		close(errCh)

		// Check if there were any errors
		for err := range errCh {
			if err != nil {
				fmt.Printf("error uploading an object: %v\n", err.Error())
				return err
			}
		}

		// List object versions after all uploads
		ctx, cancel := context.WithTimeout(context.Background(), shortTimeout)
		res, err := s3client.ListObjectVersions(ctx, &s3.ListObjectVersionsInput{
			Bucket: &bucket,
		})
		cancel()
		if err != nil {
			return err
		}

		if len(res.Versions) != versionCount {
			return fmt.Errorf("expected %v object versions, instead got %v", versionCount, len(res.Versions))
		}

		return nil
	}, withVersioning())
}
```

**Comment by benmcclelland** [comment]
Looks like the concurrent versions are still not fixed. We can work on that in the next PR:
```
RUN  Versioninig_concurrent_upload_object
22:44:09 | 200 |     581.559µs | 127.0.0.1 | PUT | /test-bucket-360 | - | 
22:44:09 | 200 |     585.125µs | 127.0.0.1 | PUT | /test-bucket-360 | - | versioning=
22:44:09 | 200 |    1.210685ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
22:44:09 | 200 |     1.21894ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
22:44:09 | 200 |    1.224441ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
uploaded object successfully: versionId: 01J9MJF0VWW0RC7KJRXNTSFQTP
22:44:09 | 200 |    1.502479ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
uploaded object successfully: versionId: 01J9MJF0VWW0RC7KJRXK3KQM2H
uploaded object successfully: versionId: 01J9MJF0VWW0RC7KJRXQG08SP7
uploaded object successfully: versionId: 01J9MJF0VWW0RC7KJRXN4AH7KM
22:44:09 | 200 |     1.66776ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
uploaded object successfully: versionId: 01J9MJF0VX9VZCTNZWXQFAV089
22:44:09 | 200 |     854.298µs | 127.0.0.1 | GET | /test-bucket-360 | - | versions=
FAIL Versioninig_concurrent_upload_object: expected 5 object versions, instead got 2
22:44:09 | 200 |     891.939µs | 127.0.0.1 | GET | /test-bucket-360 | - | versions=
22:44:10 | 204 |     847.886µs | 127.0.0.1 | DELETE | /test-bucket-360/my-obj | - | versionId=01J9MJF0VX9VZCTNZWXQFAV089&x-id=DeleteObject
22:44:10 | 204 |     636.921µs | 127.0.0.1 | DELETE | /test-bucket-360/my-obj | - | versionId=01J9MJF0VWW0RC7KJRXQG08SP7&x-id=DeleteObject
22:44:10 | 204 |     564.626µs | 127.0.0.1 | DELETE | /test-bucket-360 | - | 
```

**Comment by jonaustin09** [comment]
> Looks like the concurrent versions are still not fixed. We can work on that in the next PR:
> 
> ```
> RUN  Versioninig_concurrent_upload_object
> 22:44:09 | 200 |     581.559µs | 127.0.0.1 | PUT | /test-bucket-360 | - | 
> 22:44:09 | 200 |     585.125µs | 127.0.0.1 | PUT | /test-bucket-360 | - | versioning=
> 22:44:09 | 200 |    1.210685ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
> 22:44:09 | 200 |     1.21894ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
> 22:44:09 | 200 |    1.224441ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
> uploaded object successfully: versionId: 01J9MJF0VWW0RC7KJRXNTSFQTP
> 22:44:09 | 200 |    1.502479ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
> uploaded object successfully: versionId: 01J9MJF0VWW0RC7KJRXK3KQM2H
> uploaded object successfully: versionId: 01J9MJF0VWW0RC7KJRXQG08SP7
> uploaded object successfully: versionId: 01J9MJF0VWW0RC7KJRXN4AH7KM
> 22:44:09 | 200 |     1.66776ms | 127.0.0.1 | PUT | /test-bucket-360/my-obj | - | x-id=PutObject
> uploaded object successfully: versionId: 01J9MJF0VX9VZCTNZWXQFAV089
> 22:44:09 | 200 |     854.298µs | 127.0.0.1 | GET | /test-bucket-360 | - | versions=
> FAIL Versioninig_concurrent_upload_object: expected 5 object versions, instead got 2
> 22:44:09 | 200 |     891.939µs | 127.0.0.1 | GET | /test-bucket-360 | - | versions=
> 22:44:10 | 204 |     847.886µs | 127.0.0.1 | DELETE | /test-bucket-360/my-obj | - | versionId=01J9MJF0VX9VZCTNZWXQFAV089&x-id=DeleteObject
> 22:44:10 | 204 |     636.921µs | 127.0.0.1 | DELETE | /test-bucket-360/my-obj | - | versionId=01J9MJF0VWW0RC7KJRXQG08SP7&x-id=DeleteObject
> 22:44:10 | 204 |     564.626µs | 127.0.0.1 | DELETE | /test-bucket-360 | - | 
> ```

Ahh, okay. Please remove the last line in the PR description, which refers to concurrent version uploads issue(841).

**Review by jonaustin09 — APPROVED** [review]
