### PR TITLE
fix: Changed the GetBucketVersioning action return type, to return em…

### LINKED ISSUE #840: [Bug] - GetBucketVersioning should return empty response for unset versioning config
**Describe the bug**
GetBucketVersioning should returns non-empty response, when attempting to get unset bucket versioning configuration
Sample response from AWS CLI:
```
{
    "Status": ""
}
```

**To Reproduce**
```
// create a bucket
aws s3api create-bucket --bucket test
// get bucket versioning
aws s3api get-bucket-versioning --bucket test 
```

**Expected behavior**
The action should response empty response.

### PR DESCRIPTION
**Pull request by jonaustin09**
Fixes #840

Changed `GetBucketVersioning` response type to return empty response when versioning is not set(Enabled, Suspended).

### CODE REVIEW

File: backend/backend.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ type Backend interface {
 	PutBucketAcl(_ context.Context, bucket string, data []byte) error
 	DeleteBucket(context.Context, *s3.DeleteBucketInput) error
 	PutBucketVersioning(_ context.Context, bucket string, status types.BucketVersioningStatus) error
-	GetBucketVersioning(_ context.Context, bucket string) (*s3.GetBucketVersioningOutput, error)
+	GetBucketVersioning(_ context.Context, bucket string) (*s3response.GetBucketVersioningOutput, error)
```
Comment (benmcclelland) [inline backend/backend.go]: make this s3response.GetBucketVersioningOutput instead of a pointer to match other s3response types

File: s3response/s3response.go [hunk 2]
```diff
@@ -384,3 +384,9 @@ type ListVersionsResult struct {
 	VersionIdMarker     *string
 	Versions            []types.ObjectVersion `xml:"Version"`
 }
+
+type GetBucketVersioningOutput struct {
+	XMLName   xml.Name `xml:"http://s3.amazonaws.com/doc/2006-03-01/ VersioningConfiguration" json:"-"`
+	MFADelete *types.MFADeleteStatus
+	Status    *types.BucketVersioningStatus
```
Comment (benmcclelland) [inline s3response/s3response.go:391]: I think these need an omitempty xml tag

**Review by benmcclelland — CHANGES_REQUESTED** [review]

File: s3response/s3response.go (hunk 2 above)
Comment (benmcclelland) [reply s3response/s3response.go:391]: oh, does nil achieve this already? I didnt realize these are pointers before. that might make it so oomitempty is not needed.

**Review by benmcclelland — APPROVED** [review]
