### PR TITLE
fix: fixes PutBucketCors CORSRules validation

### LINKED ISSUE #1863: [Bug] - REST CORS - malformed `CORSRule` elements are allowed through
**Describe the bug**
Per https://docs.aws.amazon.com/AmazonS3/latest/API/API_CORSRule.html
* `CORSRule` requires `AllowedOrigin` and `AllowedMethod` tags
* `AllowedOrigin` can be blank, but `AllowedMethod` cannot be

versitygw allows empty `CORSRule` elements, elements that are missing `AllowedOrigin` or `AllowedMethod`, and elements where the `AllowedMethod` value is blank.

**To Reproduce**
1. Start versitygw, e.g.:  `./versitygw --access=AKIA**** --secret=******** --region=us-east-1 --cert /Users/lukemccrone/devel/versitygw/cert.pem --key /Users/lukemccrone/devel/versitygw/versitygw.pem posix --versioning-dir /tmp/versioning /tmp/gw`
2. Create a bucket, e.g.:  `curl -ks -w %{http_code} -X PUT https://localhost:7070/versity-gwtest-bucket-one-1-20260217140941 -H Authorization: AWS4-HMAC-SHA256 Credential=AKIA6****/20260217/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=a89a8c728cc90828e17d72e61d37142e2153314667eca5aca6202b2befa3a59a -H host: localhost:7070 -H x-amz-content-sha256: UNSIGNED-PAYLOAD -H x-amz-date: 20260217T170942Z -o /Users/lukemccrone/devel/versitygw/versity-gwtest-files/output.txt`
3. Send a **PutBucketCors** command with a malformed `CORSRule`, e.g.: 
```
PUT /versity-gwtest-bucket-one-1-20260217140941?cors HTTP/1.1<CR>
Authorization: AWS4-HMAC-SHA256 Credential=AKIA6****/20260217/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=3ea5cb9def6d05fa167059ef3606723df978dcf8bcc9870f6be3759fd4348404<CR>
Content-Length:146<CR>
Content-MD5:35Y0Jqd4FHQ02lIRq0XJWA==<CR>
host:localhost:7070<CR>
x-amz-content-sha256:595882cafa55428b23a62b881a891456397f5811f3372343c0d4c8eb1919e8df<CR>
x-amz-date:20260217T170942Z<CR>
x-amz-decoded-content-length:146<CR>
<CR>
<?xml version="1.0" encoding="UTF-8"?><CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule></CORSRule></CORSConfiguration>
```

**Expected behavior**
The error returned matches that of S3, e.g.:
```
<?xml version="1.0" encoding="UTF-8"?>
   <Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>8FF0RQFTFKWTSX38</RequestId><HostId>HdcNpgKMUB2FyKOpYtHT4rtLp5mXS1l53w9hSD9NssWmsa2qGcBBJmxJHjlvcy/+QO7rU5Oz0dw=</HostId></Error>
```
or in the case of an empty `AllowedMethod`:
```
<?xml version="1.0" encoding="UTF-8"?>
   <Error><Code>InvalidRequest</Code><Message>Found unsupported HTTP method in CORS config. Unsupported method is </Message><RequestId>RREBMYZZC6JR0T6P</RequestId><HostId>t1ONSBAoPjnOeSIr0ArxU380LLu7sZNqR7VkA8ekUdVvaVkihHfpwBzw9eKwPtT/XobSbrQnP4U=</HostId></Error>
```

**Server Version**
Version  : v1.2.0
Build    : 6c39508
BuildTime: 2026-02-17_11:32:58AM
Darwin Lukes-MacBook-Pro.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:30 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6030 arm64

### LINKED ISSUE #1870: [Bug] - REST CORS - `AllowedOrigin` double wildcards not being rejected
**Describe the bug**
With S3, attempting to add a double wildcard results in a 400 error similar to the following:
```
   <?xml version="1.0" encoding="UTF-8"?>
   <Error><Code>InvalidRequest</Code><Message>AllowedOrigin "*example*.com" can not have more than one wildcard.</Message><RequestId>5D76H0SG74CGTJVH</RequestId><HostId>IAt93lip+HTdv+SSZd2Fcentkebmr7EEWFcddtuIEBj0Qselnjo6NIpxmbBBbrMT8mLTWL/7ELU=</HostId></Error>
```
In versitygw, this gets through.

**To Reproduce**
1.  Start versitygw, e.g.:  `./versitygw --access=AKIA**** --secret=******** --region=us-east-1 --cert /Users/lukemccrone/devel/versitygw/cert.pem --key /Users/lukemccrone/devel/versitygw/versitygw.pem posix --versioning-dir /tmp/versioning /tmp/gw`
2. Create a bucket, e.g.:  `curl -ks -w %{http_code} -X PUT https://localhost:7070/versity-gwtest-bucket-one-1-20260218124558 -H Authorization: AWS4-HMAC-SHA256 Credential=AKIA6****/20260218/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=082207ef9f5349f40517b32129f2d0559add71489ef438346ca2162abd24a320 -H host: localhost:7070 -H x-amz-content-sha256: UNSIGNED-PAYLOAD -H x-amz-date: 20260218T154559Z -o /Users/lukemccrone/devel/versitygw/versity-gwtest-files/output.txt`
3. Attempt to add a `CORSRule` with a double wildcard `AllowedOrigin`, e.g.:
```
   PUT /versity-gwtest-bucket-one-1-20260218124558?cors HTTP/1.1<CR>
   Authorization: AWS4-HMAC-SHA256 Credential=AKIA6****/20260218/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=809cdc483e53c75efe8c9cbfd2ed7f2c2626783861e3772a3cf9c1dd6c5edf3d<CR>
   Content-Length:224<CR>
   Content-MD5:XW/nEpOyCNzz5fRezIdG+Q==<CR>
   host:localhost:7070<CR>
   x-amz-content-sha256:234b4408d5d8c414352c66767402b10fd5db9e7b0498625255ca5dd8c44bccd1<CR>
   x-amz-date:20260218T154559Z<CR>
   x-amz-decoded-content-length:224<CR>
   <CR>
   <?xml version="1.0" encoding="UTF-8"?><CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedOrigin>*example*.com</AllowedOrigin><AllowedMethod>GET</AllowedMethod></CORSRule></CORSConfiguration>
```

**Expected behavior**
Rejected with error matching that of S3.

**Server Version**
Version  : v1.2.0
Build    : 6c39508
BuildTime: 2026-02-17_11:32:58AM
Darwin Lukes-MacBook-Pro.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:30 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6030 arm64

### PR DESCRIPTION
**Pull request by niksis02**
Fixes #1870
Fixes #1863

A validation has been added to **PutBucketCors** for `CORSRule.AllowedOrigins`. The `AllowedOrigins` list can no longer be empty—otherwise a **MalformedXML** error is returned. Additionally, each origin is now validated to ensure it does not contain more than one wildcard.

A similar validation has been added for `AllowedMethods`. The list must not be empty, or a **MalformedXML** error is returned. Previously, empty method values (e.g., `[]string{""}`) were incorrectly treated as valid. This has been fixed, and an **UnsupportedCORSMethod** error is now returned.

### CODE REVIEW

File: auth/bucket_cors.go [hunk 1]
```diff
@@ -67,6 +70,27 @@ func (cm CORSHTTPMethod) String() string {
...
 }
 
+// String converts the origin value to 'string'
+func (co CORSOrigin) String() string {
+	return string(co)
+}
+
+// Validate validates the cors allowed origin
+func (co CORSOrigin) Validate() error {
+	// make sure no double wild card present
```
Comment (benmcclelland) [inline auth/bucket_cors.go]: do we need an empty string test here?
```go
if co == "" {
    return s3err.GetAPIError(s3err.ErrMalformedXML)
}
```

File: auth/bucket_cors.go [hunk 2]
```diff
@@ -67,6 +70,27 @@ func (cm CORSHTTPMethod) String() string {
...
+	count := 0
+	for _, char := range co {
+		if char == '*' {
+			count++
+		}
+		if count > 1 {
+			return s3err.GetMultipleWildcardCORSOriginErr(co.String())
+		}
+	}
```
Comment (benmcclelland) [inline auth/bucket_cors.go]: comsider using strings.Count:
```go
    if strings.Count(string(co), "*") > 1 {
        return s3err.GetMultipleWildcardCORSOriginErr(co.String())
    }
```

File: s3err/s3err.go [hunk 3]
```diff
@@ -1036,6 +1036,14 @@ func GetInvalidCORSRequestHeaderErr(header string) APIError {
 	}
 }
 
+func GetMultipleWildcardCORSOriginErr(origin string) APIError {
+	return APIError{
+		Code:           "InvalidRequest",
+		Description:    fmt.Sprintf(`AllowedOrigin "%s" can not have more than one wildcard.`, origin),
```
Comment (benmcclelland) [inline s3err/s3err.go:1042]: cannot

File: auth/bucket_cors_test.go [hunk 4]
```diff
@@ -22,6 +22,29 @@ import (
 	"github.com/versity/versitygw/s3err"
 )
 
+func TestCORSOrigin_Validate(t *testing.T) {
+	tests := []struct {
+		name  string // description of this test case
+		input string
+		err   error
+	}{
+		{"invalid double wildcard", "*hello*", s3err.GetMultipleWildcardCORSOriginErr("*hello*")},
```
Comment (benmcclelland) [inline auth/bucket_cors_test.go:31]: should we have an empty string test?

File: auth/bucket_cors.go (hunk 1 above)
Comment (niksis02) [reply auth/bucket_cors.go]: Yeah that's intended. Weirdly an empty string origin is considered valid by S3.

File: s3err/s3err.go (hunk 3 above)
Comment (niksis02) [reply s3err/s3err.go:1042]: This is the exact error message returned by S3: no custom text corrections by me.

example on S3:
```
An error occurred (InvalidRequest) when calling the PutBucketCors operation: AllowedOrigin "http://www.example.com**" can not have more than one wildcard.
```

**Comment by niksis02** [comment]
> only real concern here is that "" bypasses CORSOrigin.Validate(), and I'm not sure if thats intended or not.

Weirdly in S3 an empty list of origins isn't valid, but a list containing an empty string origin is. Intentionnaly I didn't add a validation for that.

File: s3err/s3err.go (hunk 3 above)
Comment (benmcclelland) [reply s3err/s3err.go:1042]: oh, hah, i was just assuming that was a typo. yeah lets keep in sync with AWS here
