### PR TITLE
fix: include all request signed headers in signature canonical string

### LINKED ISSUE #457: headers not set but listed in the signed header list cause signature validation failure
**Describe the bug**
This is a bit buggy of a client, but works against aws and other s3 services. So probably should work against the gateway as well. This shows the server side debug:
```
2024/03/14 04:38:42 Request headers: 
2024/03/14 04:38:42 Host: 172.21.1.210:7070
2024/03/14 04:38:42 Content-Length: 1024
2024/03/14 04:38:42 User-Agent: Mozilla/4.0 (Compatible; samrft; libs3 3.1; Linux x86_64)
2024/03/14 04:38:42 Accept: */*
2024/03/14 04:38:42 Expires: Thu, 01 Jan 1970 00:00:00 UTC
2024/03/14 04:38:42 X-Amz-Date: 20240314T043842Z
2024/03/14 04:38:42 X-Amz-Content-Sha256: c50d82596a70be315c25950c2ff1c3e29849ce9d3458dfa3044597a7c60cb07d
2024/03/14 04:38:42 Authorization: AWS4-HMAC-SHA256 Credential=versity/20240314/us-east-1/s3/aws4_request, SignedHeaders=content-length;expires;host;transfer-encoding;x-amz-content-sha256;x-amz-date, Signature=5f562a36faa1412ac5a39bac88bc452a9bdc6d6822772b7add810e427d657466
2024/03/14 04:38:42 Expect: 100-continue
SDK 2024/03/14 04:38:42 DEBUG Request Signature:
---[ CANONICAL STRING  ]-----------------------------
PUT
/gwtest/vsmtest/randfile1

content-length:1024
expires:Thu, 01 Jan 1970 00:00:00 UTC
host:172.21.1.210:7070
x-amz-content-sha256:c50d82596a70be315c25950c2ff1c3e29849ce9d3458dfa3044597a7c60cb07d
x-amz-date:20240314T043842Z

content-length;expires;host;x-amz-content-sha256;x-amz-date
c50d82596a70be315c25950c2ff1c3e29849ce9d3458dfa3044597a7c60cb07d
---[ STRING TO SIGN ]--------------------------------
AWS4-HMAC-SHA256
20240314T043842Z
20240314/us-east-1/s3/aws4_request
957bf42911a0462396463bf61b393085ca2a267654191676f9afaf8f14d3337c
-----------------------------------------------------
```

In this case it appears the transfer-encoding is in the signed headers list, but not actually set in the request.

**To Reproduce**
This needs a buggy client, or specially crafted requests to set headers in the signed headers list that are not being set in the request. The one I am using for these tests in from [https://github.com/versity/libs3](https://github.com/versity/libs3).

**Expected behavior**
This is still expected to succeed since it works against AWS.

**Server Version**
```
Version  : 0.16
Build    : b801a700d52debbf2a485d0f809b61e5e69395b0
BuildTime: 2024-03-12T22:16:12Z
```

**Additional context**
[https://github.com/versity/libs3](https://github.com/versity/libs3)

### PR DESCRIPTION
**Pull request by benmcclelland**
Fixes #457. There are some buggy clients that include headers not actually set on the request in the signed headers list. For these we need to include them in the signature canoncal string with empty values.

### CODE REVIEW

File: s3api/utils/auth_test.go [hunk 1]
```diff
@@ -96,6 +98,8 @@ func Test_Client_UserAgent(t *testing.T) {
 			req, zeroLenSig, service, region, tdate, signedHdrs,
 			func(options *v4.SignerOptions) {
 				options.DisableURIPathEscaping = true
+				options.LogSigning = true
+				options.Logger = logging.NewStandardLogger(os.Stderr)
```
Comment (mlt180) [inline s3api/utils/auth_test.go]: Do we actually need debug logging in unit tests?

Comment (benmcclelland) [reply s3api/utils/auth_test.go]: ah no, forgot i added that!

**Review by jonaustin09 — APPROVED** [review]
